services:
  backend:
    build: ./backend
    # Chuyển resources vào trong deploy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "150M"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/GameNro
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./fontend
    ports:
      - "3001:5173" # Máy thật vào 3001, bên trong container Vite chạy 5173
    environment:
      - NODE_ENV=development
    volumes:
      - ./fontend:/usr/src/app
      - /usr/src/app/node_modules # Bảo vệ thư viện bên trong container
    stdin_open: true
    tty: true
    command: npm run dev -- --host
    depends_on:
      - backend
