version: "3.8"

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "9229:9229"
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    volumes:
      - ./backend:/app

  frontend:
    image: frontend
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3001:3000" # Máy thật dùng 3001 để không trùng với Backend
    volumes:
      - ./frontend:/app # Để sửa code là Docker cập nhật ngay
    stdin_open: true # Giữ cho React không bị tự tắt
    tty: true
    depends_on:
      - backend # Chạy Backend xong mới chạy Frontend
