services:
  backend:
    build: ./backend
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "150M"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/GameNro
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./fontend
    ports:
      - "3001:5173" 
    env_file:
      - ../.env 
    environment:
      - NODE_ENV=development
    volumes:
      - ./fontend:/usr/src/app
      - /usr/src/app/node_modules 
      - ../.env:/usr/src/app/.env 
    stdin_open: true
    tty: true
    command: npm run dev -- --host
    depends_on:
      - backend