const express = require('express');
const router = express.Router();
const { checkIsUser } = require('../middleware/authMiddleware');
const { checkMethod } = require('../middleware/checkMethod');
const UserController = require('../controllers/UserController');
const { verifyRole } = require('../middleware/authMiddleware');
router.post('/register', UserController.createUser);
router.post('/login', verifyRole('user'), UserController.loginUser);
router.post('/getUser', verifyRole('user'), UserController.getUser);
module.exports = router;
